# Generated by Django 5.2.7 on 2025-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Number'),
        ),
    ]
